Use Saman
Go

Delete [Emp].[Permission]
Go

INSERT [Emp].[Permission]  ([Title], [Group], [Key]) VALUES
  ('Insert', 'اطلاعات پایه - تعریف نماها', 'Query_Insert')
, ('Delete', 'اطلاعات پایه - تعریف نماها', 'Query_Delete')
, ('Read', 'اطلاعات پایه - تعریف نماها', 'Query_Read')
, ('Update', 'اطلاعات پایه - تعریف نماها', 'Query_Update')
, ('Insert', 'اطلاعات پایه - تعریف نماها - دسترسی ها', 'QueryEmployee_Insert')
, ('Delete', 'اطلاعات پایه - تعریف نماها - دسترسی ها', 'QueryEmployee_Delete')
, ('Read', 'اطلاعات پایه - تعریف نماها - دسترسی ها', 'QueryEmployee_Read')
, ('Read', 'اطلاعات پایه - تنظيمات SMTP', 'SmtpSettings_Read')
, ('Update', 'اطلاعات پایه - تنظيمات SMTP', 'SmtpSettings_Update')
, ('Insert', 'اطلاعات پایه - حساب هاي پولي شرکت', 'MoneyAccount_Insert')
, ('Delete', 'اطلاعات پایه - حساب هاي پولي شرکت', 'MoneyAccount_Delete')
, ('Read', 'اطلاعات پایه - حساب هاي پولي شرکت', 'MoneyAccount_Read')
, ('Update', 'اطلاعات پایه - حساب هاي پولي شرکت', 'MoneyAccount_Update')
, ('Insert', 'اطلاعات پایه - حساب هاي پولي شرکت - حرکت به بالا، پایین', 'MoneyAccount_Move')
, ('Insert', 'اطلاعات پایه - حسابهای پولی - کارمندان مجاز به تأیید', 'MoneyAccountEmployee_Insert')
, ('Delete', 'اطلاعات پایه - حسابهای پولی - کارمندان مجاز به تأیید', 'MoneyAccountEmployee_Delete')
, ('Read', 'اطلاعات پایه - حسابهای پولی - کارمندان مجاز به تأیید', 'MoneyAccountEmployee_Read')
, ('Update', 'اطلاعات پایه - حسابهای پولی - کارمندان مجاز به تأیید', 'MoneyAccountEmployee_Update')
, ('Insert', 'اطلاعات پایه - شماره هاي خاص', 'SpecialNumbers_Insert')
, ('Delete', 'اطلاعات پایه - شماره هاي خاص', 'SpecialNumbers_Delete')
, ('Read', 'اطلاعات پایه - شماره هاي خاص', 'SpecialNumbers_Read')
, ('Update', 'اطلاعات پایه - شماره هاي خاص', 'SpecialNumbers_Update')
, ('Insert', 'اطلاعات پایه - شيوه هاي جذب', 'SuctionMode_Insert')
, ('Delete', 'اطلاعات پایه - شيوه هاي جذب', 'SuctionMode_Delete')
, ('Read', 'اطلاعات پایه - شيوه هاي جذب', 'SuctionMode_Read')
, ('Update', 'اطلاعات پایه - شيوه هاي جذب', 'SuctionMode_Update')
, ('Insert', 'اطلاعات پایه - مراکز مخابراتی', 'Center_Insert')
, ('Delete', 'اطلاعات پایه - مراکز مخابراتی', 'Center_Delete')
, ('Read', 'اطلاعات پایه - مراکز مخابراتی', 'Center_Read')
, ('Update', 'اطلاعات پایه - مراکز مخابراتی', 'Center_Update')
, ('Insert', 'اطلاعات پایه - مراکز مخابراتی - پیش شماره ها', 'Code_Insert')
, ('Delete', 'اطلاعات پایه - مراکز مخابراتی - پیش شماره ها', 'Code_Delete')
, ('Read', 'اطلاعات پایه - مراکز مخابراتی - پیش شماره ها', 'Code_Read')
, ('Update', 'اطلاعات پایه - مراکز مخابراتی - پیش شماره ها', 'Code_Update')
, ('Read', 'اطلاعات پایه - مراکز مخابراتی - وضعیت پوشش', 'NetworkCenter_Read')
, ('Update', 'اطلاعات پایه - مراکز مخابراتی - وضعیت پوشش', 'NetworkCenter_Update')
, ('Insert', 'اطلاعات پایه - نمايندگي ها', 'Agency_Insert')
, ('Delete', 'اطلاعات پایه - نمايندگي ها', 'Agency_Delete')
, ('Read', 'اطلاعات پایه - نمايندگي ها', 'Agency_Read')
, ('Update', 'اطلاعات پایه - نمايندگي ها', 'Agency_Update')
, ('Insert', 'اطلاعات پایه - وضعيت مدارک', 'DocumentStatus_Insert')
, ('Delete', 'اطلاعات پایه - وضعيت مدارک', 'DocumentStatus_Delete')
, ('Read', 'اطلاعات پایه - وضعيت مدارک', 'DocumentStatus_Read')
, ('Update', 'اطلاعات پایه - وضعيت مدارک', 'DocumentStatus_Update')
, ('Insert', 'انبارهای مجازی - کالاهای انبار', 'StoreProduct_Insert')
, ('Delete', 'انبارهای مجازی - کالاهای انبار', 'StoreProduct_Delete')
, ('Read', 'انبارهای مجازی - کالاهای انبار', 'StoreProduct_Read')
, ('Update', 'انبارهای مجازی - کالاهای انبار', 'StoreProduct_Update')
, ('Insert', 'تنظیمات کارمندان - کارمندان', 'Employee_Insert')
, ('Delete', 'تنظیمات کارمندان - کارمندان', 'Employee_Delete')
, ('Read', 'تنظیمات کارمندان - کارمندان', 'Employee_Read')
, ('Update', 'تنظیمات کارمندان - کارمندان', 'Employee_Update')
, ('Read', 'تنظیمات کارمندان - کارمندان - دسترسي ها', 'EmployeePermission_Read')
, ('Update', 'تنظیمات کارمندان - کارمندان - دسترسي ها', 'EmployeePermission_Update')
, ('Insert', 'تنظیمات کارمندان - گروه های کاربری', 'Group_Insert')
, ('Delete', 'تنظیمات کارمندان - گروه های کاربری', 'Group_Delete')
, ('Read', 'تنظیمات کارمندان - گروه های کاربری', 'Group_Read')
, ('Update', 'تنظیمات کارمندان - گروه های کاربری', 'Group_Update')
, ('Read', 'تنظیمات کارمندان - گروههای کاربری - دسترسی ها', 'GroupPermission_Read')
, ('Update', 'تنظیمات کارمندان - گروههای کاربری - دسترسی ها', 'GroupPermission_Update')
, ('Insert', 'شبکه ها - شبکه ها', 'Network_Insert')
, ('Delete', 'شبکه ها - شبکه ها', 'Network_Delete')
, ('Read', 'شبکه ها - شبکه ها', 'Network_Read')
, ('Update', 'شبکه ها - شبکه ها', 'Network_Update')
, ('Insert', 'شبکه ها - شبکه ها - تراکنش مالی شبکه ها', 'NetworkCredit_Insert')
, ('Delete', 'شبکه ها - شبکه ها - تراکنش مالی شبکه ها', 'NetworkCredit_Delete')
, ('Read', 'شبکه ها - شبکه ها - تراکنش مالی شبکه ها', 'NetworkCredit_Read')
, ('Update', 'شبکه ها - شبکه ها - تراکنش مالی شبکه ها', 'NetworkCredit_Update')
, ('Insert', 'عملیات مشتری - پشتيباني حضوري', 'PersenceSupport_Insert')
, ('Delete', 'عملیات مشتری - پشتيباني حضوري', 'PersenceSupport_Delete')
, ('Read', 'عملیات مشتری - پشتيباني حضوري', 'PersenceSupports_Read')
, ('Update', 'عملیات مشتری - پشتيباني حضوري', 'PersenceSupport_Update')
, ('Insert', 'عملیات مشتری - پشتيباني حضوري - تحویل', 'PersenceSupport_Deliver')
, ('Read', 'عملیات مشتری - پيامک ها', 'Smss_Read')
, ('Insert', 'عملیات مشتری - پيامک ها - ارسال پیامک', 'Sms_Send')
, ('Insert', 'عملیات مشتری - رایانامه', 'Email_Insert')
, ('Delete', 'عملیات مشتری - رایانامه', 'Email_Delete')
, ('Read', 'عملیات مشتری - رایانامه', 'Emails_Read')
, ('Update', 'عملیات مشتری - رایانامه', 'Email_Update')
, ('Insert', 'عملیات مشتری - فروش', 'Sale_Insert')
, ('Delete', 'عملیات مشتری - فروش', 'Sale_Delete')
, ('Read', 'عملیات مشتری - فروش', 'Sales_Read')
, ('Insert', 'عملیات مشتری - فروش - اقلام فروش', 'SaleDetails_Insert')
, ('Delete', 'عملیات مشتری - فروش - اقلام فروش', 'SaleDetail_Delete')
, ('Read', 'عملیات مشتری - فروش - اقلام فروش', 'SaleDetails_Read')
, ('Update', 'عملیات مشتری - فروش - اقلام فروش', 'SaleDetail_Update')
, ('Insert', 'عملیات مشتری - فروش - اقلام فروش - تحویل', 'SaleDetail_Deliver')
, ('Insert', 'عملیات مشتری - فروش - برگشت از فروش', 'Rollback_Insert')
, ('Read', 'عملیات مشتری - فروش - برگشت از فروش', 'Rollback_Read')
, ('Insert', 'عملیات مشتری - فروش - تأیید و بستن فروش', 'CloseSale')
, ('Read', 'عملیات مشتری - فروش - لیست تحویل ها', 'SaleDetails_Deliver_Read')
, ('Insert', 'عملیات مشتری - مالی', 'Fiscal_Insert')
, ('Delete', 'عملیات مشتری - مالی', 'Fiscal_Delete')
, ('Read', 'عملیات مشتری - مالی', 'Fiscal_Read')
, ('Update', 'عملیات مشتری - مالی', 'Fiscal_Update')
, ('Read', 'عملیات مشتری - مالی - Insert شده توسط من', 'Fiscal_WithMeRead')
, ('Insert', 'عملیات مشتری - مالی - تأیید مالی', 'Fiscal_DoConfirm')
, ('Read', 'عملیات مشتری - مالی - Read همه', 'Fiscal_ReadAll')
, ('Insert', 'عملیات مشتری - مدیریت مدارک', 'Document_Insert')
, ('Delete', 'عملیات مشتری - مدیریت مدارک', 'Document_Delete')
, ('Read', 'عملیات مشتری - مدیریت مدارک', 'Document_Read')
, ('Update', 'عملیات مشتری - مدیریت مدارک', 'Document_Update')
, ('Insert', 'عملیات مشتری - مشکلات', 'Problem_Insert')
, ('Delete', 'عملیات مشتری - مشکلات', 'Problem_Delete')
, ('Read', 'عملیات مشتری - مشکلات', 'Problems_Read')
, ('Update', 'عملیات مشتری - مشکلات', 'Problem_Update')
, ('Insert', 'عملیات مشتري - تغییر مرحله مشتری', 'Change_Level')
, ('Insert', 'کالاها و خدمات - انبارهای مجازی کالا', 'Store_Insert')
, ('Delete', 'کالاها و خدمات - انبارهای مجازی کالا', 'Store_Delete')
, ('Read', 'کالاها و خدمات - انبارهای مجازی کالا', 'Store_Read')
, ('Update', 'کالاها و خدمات - انبارهای مجازی کالا', 'Store_Update')
, ('Insert', 'کالاها و خدمات - خدمات اعتباري', 'CreditService_Insert')
, ('Delete', 'کالاها و خدمات - خدمات اعتباري', 'CreditService_Delete')
, ('Read', 'کالاها و خدمات - خدمات اعتباري', 'CreditService_Read')
, ('Update', 'کالاها و خدمات - خدمات اعتباري', 'CreditService_Update')
, ('Insert', 'کالاها و خدمات - خدمات غير اعتباري', 'UncreditService_Insert')
, ('Delete', 'کالاها و خدمات - خدمات غير اعتباري', 'UncreditService_Delete')
, ('Read', 'کالاها و خدمات - خدمات غير اعتباري', 'UncreditService_Read')
, ('Update', 'کالاها و خدمات - خدمات غير اعتباري', 'UncreditService_Update')
, ('Insert', 'کالاها و خدمات - کالاها - ورود و خروج کلی', 'ProductLog_Insert')
, ('Read', 'کالاها و خدمات - کالاها - ورود و خروج کلی', 'ProductLog_Read')
, ('Insert', 'کالاها و خدمات - کالاهای پایه', 'Product_Insert')
, ('Delete', 'کالاها و خدمات - کالاهای پایه', 'Product_Delete')
, ('Read', 'کالاها و خدمات - کالاهای پایه', 'Product_Read')
, ('Update', 'کالاها و خدمات - کالاهای پایه', 'Product_Update')
, ('Insert', 'کالاها و خدمات - کالاهای پایه - محصولات', 'ProductPrice_Insert')
, ('Delete', 'کالاها و خدمات - کالاهای پایه - محصولات', 'ProductPrice_Delete')
, ('Read', 'کالاها و خدمات - کالاهای پایه - محصولات', 'ProductPrice_Read')
, ('Update', 'کالاها و خدمات - کالاهای پایه - محصولات', 'ProductPrice_Update')
, ('Insert', 'گردش کار - انواع مرحله', 'LevelType_Insert')
, ('Delete', 'گردش کار - انواع مرحله', 'LevelType_Delete')
, ('Read', 'گردش کار - انواع مرحله', 'LevelType_Read')
, ('Update', 'گردش کار - انواع مرحله', 'LevelType_Update')
, ('Insert', 'گردش کار - تعریف شروط', 'Condition_Insert')
, ('Delete', 'گردش کار - تعریف شروط', 'Condition_Delete')
, ('Read', 'گردش کار - تعریف شروط', 'Condition_Read')
, ('Update', 'گردش کار - تعریف شروط', 'Condition_Update')
, ('Read', 'گردش کار - فلوچارت مراحل', 'Relation_Read')
, ('Insert', 'گردش کار - مراحل', 'Level_Insert')
, ('Delete', 'گردش کار - مراحل', 'Level_Delete')
, ('Read', 'گردش کار - مراحل', 'Level_Read')
, ('Update', 'گردش کار - مراحل', 'Level_Update')
, ('Insert', 'گردش کار - مراحل - شروط مراحل', 'LevelCondition_Insert')
, ('Delete', 'گردش کار - مراحل - شروط مراحل', 'LevelCondition_Delete')
, ('Read', 'گردش کار - مراحل - شروط مراحل', 'LevelCondition_Read')
, ('Update', 'گردش کار - مراحل - شروط مراحل', 'LevelCondition_Update')
, ('Insert', 'گردش کار - مراحل - مراحل بعد', 'RelatedLevel_Create')
, ('Delete', 'گردش کار - مراحل - مراحل بعد', 'RelatedLevel_Delete')
, ('Read', 'گردش کار - مراحل - مراحل بعد', 'RelatedLevel_Read')
, ('Read', 'گزارشات - فاکتور فروش', 'Report_Factor')
, ('Read', 'گزارشات - قبض صندوق', 'Report_Cash')
, ('Read', 'گزارشات - کارتکس کالای انبار اصلی', 'Report_MainCartexReport')
, ('Read', 'گزارشات - معین مشتری', 'Report_LedgerAccount')
, ('Insert', 'مشتری', 'Customer_Insert')
, ('Delete', 'مشتری', 'Customer_Delete')
, ('Read', 'مشتری', 'Customer_Read')
, ('Update', 'مشتری', 'Customer_Update')
, ('Insert', 'مشتریان - يادداشت ها', 'Note_Insert')
, ('Delete', 'مشتریان - يادداشت ها', 'Note_Delete')
, ('Read', 'مشتریان - يادداشت ها', 'Note_Read')
, ('Update', 'مشتریان - يادداشت ها', 'Note_Update')
