//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kendo.Mvc.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kendo.Mvc.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قلم کلفت.
        /// </summary>
        public static string Editor_Bold {
            get {
                return ResourceManager.GetString("Editor_Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافه کردن هایپرلینک.
        /// </summary>
        public static string Editor_CreateLink {
            get {
                return ResourceManager.GetString("Editor_CreateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب فونت.
        /// </summary>
        public static string Editor_FontName {
            get {
                return ResourceManager.GetString("Editor_FontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (فونت به ارث رسیده).
        /// </summary>
        public static string Editor_FontNameInherit {
            get {
                return ResourceManager.GetString("Editor_FontNameInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب اندازه فونت.
        /// </summary>
        public static string Editor_FontSize {
            get {
                return ResourceManager.GetString("Editor_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (سایز به ارث رسیده).
        /// </summary>
        public static string Editor_FontSizeInherit {
            get {
                return ResourceManager.GetString("Editor_FontSizeInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت.
        /// </summary>
        public static string Editor_FormatBlock {
            get {
                return ResourceManager.GetString("Editor_FormatBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تو رفتگی.
        /// </summary>
        public static string Editor_Indent {
            get {
                return ResourceManager.GetString("Editor_Indent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن HTML.
        /// </summary>
        public static string Editor_InsertHtml {
            get {
                return ResourceManager.GetString("Editor_InsertHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن عکس.
        /// </summary>
        public static string Editor_InsertImage {
            get {
                return ResourceManager.GetString("Editor_InsertImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن لیست مرتب.
        /// </summary>
        public static string Editor_InsertOrderedList {
            get {
                return ResourceManager.GetString("Editor_InsertOrderedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن لیست نامرتب.
        /// </summary>
        public static string Editor_InsertUnorderedList {
            get {
                return ResourceManager.GetString("Editor_InsertUnorderedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مایل.
        /// </summary>
        public static string Editor_Italic {
            get {
                return ResourceManager.GetString("Editor_Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وسط چین.
        /// </summary>
        public static string Editor_JustifyCenter {
            get {
                return ResourceManager.GetString("Editor_JustifyCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پاراگراف.
        /// </summary>
        public static string Editor_JustifyFull {
            get {
                return ResourceManager.GetString("Editor_JustifyFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چپ چین.
        /// </summary>
        public static string Editor_JustifyLeft {
            get {
                return ResourceManager.GetString("Editor_JustifyLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to راست چین.
        /// </summary>
        public static string Editor_JustifyRight {
            get {
                return ResourceManager.GetString("Editor_JustifyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیرون رفتگی.
        /// </summary>
        public static string Editor_Outdent {
            get {
                return ResourceManager.GetString("Editor_Outdent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strikethrough.
        /// </summary>
        public static string Editor_Strikethrough {
            get {
                return ResourceManager.GetString("Editor_Strikethrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استایل ها.
        /// </summary>
        public static string Editor_Styles {
            get {
                return ResourceManager.GetString("Editor_Styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscript.
        /// </summary>
        public static string Editor_Subscript {
            get {
                return ResourceManager.GetString("Editor_Subscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superscript.
        /// </summary>
        public static string Editor_Superscript {
            get {
                return ResourceManager.GetString("Editor_Superscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        public static string Editor_Underline {
            get {
                return ResourceManager.GetString("Editor_Underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف لینک.
        /// </summary>
        public static string Editor_Unlink {
            get {
                return ResourceManager.GetString("Editor_Unlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to و.
        /// </summary>
        public static string Filter_And {
            get {
                return ResourceManager.GetString("Filter_And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف فیلتر.
        /// </summary>
        public static string Filter_Clear {
            get {
                return ResourceManager.GetString("Filter_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برابر.
        /// </summary>
        public static string Filter_DateIsEqualTo {
            get {
                return ResourceManager.GetString("Filter_DateIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بعد از.
        /// </summary>
        public static string Filter_DateIsGreaterThan {
            get {
                return ResourceManager.GetString("Filter_DateIsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برابر یا بعد از.
        /// </summary>
        public static string Filter_DateIsGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("Filter_DateIsGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبل از.
        /// </summary>
        public static string Filter_DateIsLessThan {
            get {
                return ResourceManager.GetString("Filter_DateIsLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برابر یا قبل از.
        /// </summary>
        public static string Filter_DateIsLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("Filter_DateIsLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مساوی نباشد با.
        /// </summary>
        public static string Filter_DateIsNotEqualTo {
            get {
                return ResourceManager.GetString("Filter_DateIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برابر باشد با.
        /// </summary>
        public static string Filter_EnumIsEqualTo {
            get {
                return ResourceManager.GetString("Filter_EnumIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برابر نباشد با.
        /// </summary>
        public static string Filter_EnumIsNotEqualTo {
            get {
                return ResourceManager.GetString("Filter_EnumIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلتر.
        /// </summary>
        public static string Filter_Filter {
            get {
                return ResourceManager.GetString("Filter_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش آیتمهایی با مقادیر:.
        /// </summary>
        public static string Filter_Info {
            get {
                return ResourceManager.GetString("Filter_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غلط.
        /// </summary>
        public static string Filter_IsFalse {
            get {
                return ResourceManager.GetString("Filter_IsFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درست.
        /// </summary>
        public static string Filter_IsTrue {
            get {
                return ResourceManager.GetString("Filter_IsTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برابر باشد با.
        /// </summary>
        public static string Filter_NumberIsEqualTo {
            get {
                return ResourceManager.GetString("Filter_NumberIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بزرگتر از.
        /// </summary>
        public static string Filter_NumberIsGreaterThan {
            get {
                return ResourceManager.GetString("Filter_NumberIsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بزرگتر یا مساوی.
        /// </summary>
        public static string Filter_NumberIsGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("Filter_NumberIsGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کمتر از.
        /// </summary>
        public static string Filter_NumberIsLessThan {
            get {
                return ResourceManager.GetString("Filter_NumberIsLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کمتر یا مساوی.
        /// </summary>
        public static string Filter_NumberIsLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("Filter_NumberIsLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برابر نباشد با.
        /// </summary>
        public static string Filter_NumberIsNotEqualTo {
            get {
                return ResourceManager.GetString("Filter_NumberIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یا.
        /// </summary>
        public static string Filter_Or {
            get {
                return ResourceManager.GetString("Filter_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -انتخاب مقدار-.
        /// </summary>
        public static string Filter_SelectValue {
            get {
                return ResourceManager.GetString("Filter_SelectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شامل.
        /// </summary>
        public static string Filter_StringContains {
            get {
                return ResourceManager.GetString("Filter_StringContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شامل نباشد.
        /// </summary>
        public static string Filter_StringDoesNotContain {
            get {
                return ResourceManager.GetString("Filter_StringDoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمام می شود با.
        /// </summary>
        public static string Filter_StringEndsWith {
            get {
                return ResourceManager.GetString("Filter_StringEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برابر باشد با.
        /// </summary>
        public static string Filter_StringIsEqualTo {
            get {
                return ResourceManager.GetString("Filter_StringIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برابر نباشد با.
        /// </summary>
        public static string Filter_StringIsNotEqualTo {
            get {
                return ResourceManager.GetString("Filter_StringIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروع می شود با.
        /// </summary>
        public static string Filter_StringStartsWith {
            get {
                return ResourceManager.GetString("Filter_StringStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کنسل.
        /// </summary>
        public static string Grid_Cancel {
            get {
                return ResourceManager.GetString("Grid_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کنسل کردن تغییرات.
        /// </summary>
        public static string Grid_CancelChanges {
            get {
                return ResourceManager.GetString("Grid_CancelChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ستون ها.
        /// </summary>
        public static string Grid_Columns {
            get {
                return ResourceManager.GetString("Grid_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا از حذف این آیتمها مطمئن هستید؟.
        /// </summary>
        public static string Grid_Confirmation {
            get {
                return ResourceManager.GetString("Grid_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد.
        /// </summary>
        public static string Grid_Create {
            get {
                return ResourceManager.GetString("Grid_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string Grid_Destroy {
            get {
                return ResourceManager.GetString("Grid_Destroy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش.
        /// </summary>
        public static string Grid_Edit {
            get {
                return ResourceManager.GetString("Grid_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره تغییرات.
        /// </summary>
        public static string Grid_SaveChanges {
            get {
                return ResourceManager.GetString("Grid_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب.
        /// </summary>
        public static string Grid_Select {
            get {
                return ResourceManager.GetString("Grid_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرتب کردن صعودی.
        /// </summary>
        public static string Grid_SortAscending {
            get {
                return ResourceManager.GetString("Grid_SortAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرتب کردن نزولی.
        /// </summary>
        public static string Grid_SortDescending {
            get {
                return ResourceManager.GetString("Grid_SortDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره.
        /// </summary>
        public static string Grid_Update {
            get {
                return ResourceManager.GetString("Grid_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای گروه بندی بر اساس ستون، یکی از ستونها را بکشید و اینجا رها کنید.
        /// </summary>
        public static string Group_Empty {
            get {
                return ResourceManager.GetString("Group_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1} از {2} آیتم.
        /// </summary>
        public static string Pager_Display {
            get {
                return ResourceManager.GetString("Pager_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیج آیتمی جهت نمایش وجود ندارد.
        /// </summary>
        public static string Pager_Empty {
            get {
                return ResourceManager.GetString("Pager_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برو به صفحه اول.
        /// </summary>
        public static string Pager_First {
            get {
                return ResourceManager.GetString("Pager_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیتم در هر صفحه.
        /// </summary>
        public static string Pager_ItemsPerPage {
            get {
                return ResourceManager.GetString("Pager_ItemsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برو به صفحه آخر.
        /// </summary>
        public static string Pager_Last {
            get {
                return ResourceManager.GetString("Pager_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برو به صفحه بعد.
        /// </summary>
        public static string Pager_Next {
            get {
                return ResourceManager.GetString("Pager_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از {0}.
        /// </summary>
        public static string Pager_Of {
            get {
                return ResourceManager.GetString("Pager_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه.
        /// </summary>
        public static string Pager_Page {
            get {
                return ResourceManager.GetString("Pager_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برو به صفحه قبل.
        /// </summary>
        public static string Pager_Previous {
            get {
                return ResourceManager.GetString("Pager_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به هنگام سازی.
        /// </summary>
        public static string Pager_Refresh {
            get {
                return ResourceManager.GetString("Pager_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغو.
        /// </summary>
        public static string Upload_Cancel {
            get {
                return ResourceManager.GetString("Upload_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای آپلود کردن فایلها را بکشید و اینجا رها کنید.
        /// </summary>
        public static string Upload_DropFilesHere {
            get {
                return ResourceManager.GetString("Upload_DropFilesHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string Upload_Remove {
            get {
                return ResourceManager.GetString("Upload_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعی دوباره.
        /// </summary>
        public static string Upload_Retry {
            get {
                return ResourceManager.GetString("Upload_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب...‏.
        /// </summary>
        public static string Upload_Select {
            get {
                return ResourceManager.GetString("Upload_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آپلود ناموفق بود.
        /// </summary>
        public static string Upload_StatusFailed {
            get {
                return ResourceManager.GetString("Upload_StatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آپلود شد.
        /// </summary>
        public static string Upload_StatusUploaded {
            get {
                return ResourceManager.GetString("Upload_StatusUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال آپلود شدن.
        /// </summary>
        public static string Upload_StatusUploading {
            get {
                return ResourceManager.GetString("Upload_StatusUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آپلود کردن فایل.
        /// </summary>
        public static string Upload_UploadSelectedFiles {
            get {
                return ResourceManager.GetString("Upload_UploadSelectedFiles", resourceCulture);
            }
        }
    }
}
